dist: xenial
addons:
  chrome: stable
language: node_js
install:
- npm ci
- npm run webdriver:update
cache:
  directories:
  - node_modules
env:
  global:
  - secure: O1pfQJd+KkHJuvZU1B+w9+iFn7aRkXacX2UMsvSZVSu7FVoyggh7B8efrxHMEiU0RqmRB9GOJ6Bq6GdJLqFPpipucRxcH3mF4Ab9DjblCzGmAFEiY1xjo23XpwJdgqS/HIDCSsZaoIx8nZhMwpFe72aW9m5BW0gTvCwQJ5MLVu3oWnJrJw/eyWB4nk4B6x3m+dwBKKBG189TxZcpFxc7uPVniGSTb/bUhQ4MzGaLJvqX8J7D+rBMipXY/ah438U3TpzCI0hY72X010JgsSOGHEyEQsaL0OAO2LF704ohQ+MsXnibakNycmb/PZMglBu2xWkCogSz0D50CtQTJ3MiHpkeIwznA4yQK8xWfgK9fKbd+v/dC86/5JueC1AK+xE8tmZweUyJZn1phAUB3TiBkcwUyzQ3AFk2EoN/gQtmNfogzHYm1VZ5Q5lxYYvF3cNxFh159g5tRZsadF4v+6XBGJ27Q5ts1hQkvKogayd2BkUo4rd2WLBRCq0qr0u32a9kkSGhsvxS3puK26jRjeADN0JU1Mn29Tl/fS41pxChufzYc7/OblDd4SdKNs6trolt4JJDFzUGxinKTwq3Pr7llyEkXIJiWA0wAl6Rbs0K45ECTFlvFaGgfTm37uzjjWMnB5OKzwx02AuDsx6oomo4zzPQj2x/suW6zcjwhqc5Vlo=
  - secure: ioKX5HIahYbUFK7sJm5Qhwbxno6rTlX1OwQF1K01wRZ67dSpJtIiLCs7TKkmOv7W0h/PUM2QxqIcPQs/VXiXLw5obqr93oDxUH2ntV2VqLSLk46cIyWPqGchW2l9nLM5ooiaNSh3/j6VrBwIiUMyuS1+Vei08X9uHsZAY+SDwi8RwGCImhgF+NL3ZqkXWpNn/Vr+NuN18Lo6iS6TXKSZS+J1EslhGqzr0yYN0HxUr7wfwq03Uh4X6dfPiZ6qTk8T1+QfssvGAPd13eCn0mrh1aME/xN4UbSRvsInKxeripSSMzRI3LVxdNjIb58BKwdhnqQG0cDsr5DkHNODU4+oGpNRJZ+E+nbgG35UXAlWLSglXr4QZHS83487RzEtqbUQwvrr6upotd+Yfyw5ylUPDcQ3T1XbqGJNbJl0xVTXnKLvKsthG1EEJzeOZpANc0t3qXxnwrombIXwNALGB4muLnjH89eof533E6KwvpiRevaqUec8T3mCswTXTpCPDaxX4xVeAZ7oZgWuF5rh50Axe1JFesiWtsj8ey4bnq6cclxNgRNO75HoUp+uBwc8zKMVUNMsFPtgtXTEnQrgwzxh13XpOPLbI1zWL7dI6dbPT3FywFhbNqebDGzUj9LvA907bCDHhGLacncLaOT5SUnLqpfxQtONyitALGNhIBPEAW0=